### PR TITLE
Prevent going offline when restoring or taking a snapshot

### LINKED ISSUE #6484: Warp sync failing on fresh DB
> I'm running:
>
> - **Parity version**: v1.8.0-unstable-7ddbc6c-20170906/x86_64-linux-gnu/rustc1.21.0-beta.2
> - **Operating system**: Linux
> - **And installed**: from source
---

Warp sync failed with no apparent reason, and wouldn't continue at all later.

```
$ ./target/release/parity --chain=foundation --db-path ~/.local/share/io.parity.ethereum/others/alt-db/
Loading config file from /home/tomusdrw/.local/share/io.parity.ethereum/config.toml
2017-09-08 13:16:37  main INFO parity::run  Starting Parity/v1.8.0-unstable-7ddbc6c-20170906/x86_64-linux-gnu/rustc1.21.0-beta.2
2017-09-08 13:16:37  main INFO parity::run  Keys path /home/tomusdrw/.local/share/io.parity.ethereum/keys/Foundation
2017-09-08 13:16:37  main INFO parity::run  DB path /home/tomusdrw/.local/share/io.parity.ethereum/others/alt-db/ethereum/db/906a34e69aec8c0d
2017-09-08 13:16:37  main INFO parity::run  Path to dapps /home/tomusdrw/.local/share/io.parity.ethereum/dapps
2017-09-08 13:16:37  main INFO parity::run  State DB configuration: fast
2017-09-08 13:16:37  main INFO parity::run  Operating mode: passive
2017-09-08 13:16:37  main INFO ethcore::service  Configured for Foundation using Ethash engine
2017-09-08 13:16:38   INFO miner  Updated conversion rate to Ξ1 = US$332.45 (358091780 wei/gas)
2017-09-08 13:16:38  IO Worker #2 INFO network  Public node URL: enode://aab61610f7040ffa00fe1af5e243f4a3422dcf479be3a12f8477e778e84b5745d704fdfa7440321884c29b679e9631a978e9ed36d5c52b0d215f6d299c762e68@192.168.1.113:30303
2017-09-08 13:16:38  main WARN dapps  Cannot read manifest file at: "/home/tomusdrw/.local/share/io.parity.ethereum/dapps/mindapp/manifest.json". Error: "Error { repr: Os { code: 2, message: \"No such file or directory\" } }"
2017-09-08 13:16:43  IO Worker #3 INFO import  Syncing snapshot 1/341        #0    5/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn, 72 req/s,  46 µs
2017-09-08 13:16:53  IO Worker #3 INFO import  Syncing snapshot 8/341        #0    6/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:16:58  IO Worker #1 INFO import  Syncing snapshot 12/341        #0    6/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:17:08  IO Worker #3 INFO import  Syncing snapshot 22/341        #0    7/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:17:18  IO Worker #3 INFO import  Syncing snapshot 31/341        #0    7/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:17:28  IO Worker #0 INFO import  Syncing snapshot 41/341        #0    7/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:17:33  IO Worker #1 INFO import  Syncing snapshot 46/341        #0    7/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:17:43  IO Worker #3 INFO import  Syncing snapshot 57/341        #0   10/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:17:53  IO Worker #1 INFO import  Syncing snapshot 66/341        #0   10/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:03  IO Worker #1 INFO import  Syncing snapshot 75/341        #0   10/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:08  IO Worker #0 INFO import  Syncing snapshot 80/341        #0   11/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:18  IO Worker #2 INFO import  Syncing snapshot 89/341        #0   11/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:28  IO Worker #1 INFO import  Syncing snapshot 98/341        #0   11/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:38  IO Worker #0 INFO import  Syncing snapshot 107/341        #0   12/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:48  IO Worker #1 INFO import  Syncing snapshot 116/341        #0   16/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:18:58  IO Worker #3 INFO import  Syncing snapshot 124/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:08  IO Worker #2 INFO import  Syncing snapshot 134/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:18  IO Worker #2 INFO import  Syncing snapshot 143/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:23  IO Worker #3 INFO import  Syncing snapshot 147/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:28  IO Worker #3 INFO import  Syncing snapshot 151/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:39  IO Worker #0 INFO import  Syncing snapshot 159/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:48  IO Worker #2 INFO import  Syncing snapshot 169/341        #0   19/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:19:58  IO Worker #3 INFO import  Syncing snapshot 176/341        #0   18/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:08  IO Worker #1 INFO import  Syncing snapshot 186/341        #0   19/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:14  IO Worker #1 INFO import  Syncing snapshot 190/341        #0   20/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:23  IO Worker #1 INFO import  Syncing snapshot 199/341        #0   20/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:28  IO Worker #0 INFO import  Syncing snapshot 203/341        #0   20/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:39  IO Worker #1 INFO import  Syncing snapshot 210/341        #0   20/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:45  IO Worker #1 INFO import  Syncing snapshot 214/341        #0   22/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:53  IO Worker #0 INFO import  Syncing snapshot 218/341        #0   22/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:20:58  IO Worker #3 INFO import  Syncing snapshot 220/341        #0   23/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:21:08  IO Worker #1 INFO import  Syncing snapshot 226/341        #0   22/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:21:13  IO Worker #1 INFO import  Syncing snapshot 227/341        #0   23/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:21:18  IO Worker #2 INFO import  Syncing snapshot 229/341        #0   24/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:21:26  IO Worker #3 INFO import  Syncing snapshot 232/341        #0   24/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:21:33  IO Worker #1 INFO import  Syncing snapshot 236/341        #0   24/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:21:43  IO Worker #0 WARN ethcore::snapshot::service  Encountered error during state restoration: Snapshot restoration aborted.
2017-09-08 13:21:43  IO Worker #1 WARN ethcore::snapshot::service  Encountered error during state restoration: Snapshot restoration aborted.
2017-09-08 13:21:43  IO Worker #3 INFO import  Syncing snapshot 243/341        #0   23/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:22:13  IO Worker #1 INFO import     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
2017-09-08 13:22:43  IO Worker #2 INFO import     0/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s,  46 µs
^C2017-09-08 13:22:44  main INFO parity::run  Finishing work, please wait...
```

### PR DESCRIPTION
**Pull request by arkpar**
Closes #6484

### CODE REVIEW

File: ethcore/src/client/client.rs [hunk 1]
```diff
@@ -1064,7 +1068,9 @@ impl Client {
 			},
 		};
 
+		self.taking_snapshot.store(true, AtomicOrdering::Relaxed);
 		snapshot::take_snapshot(&*self.engine, &self.chain.read(), start_hash, db.as_hashdb(), writer, p)?;
+		self.taking_snapshot.store(false, AtomicOrdering::Relaxed);
```
Comment (rphmeier) [inline ethcore/src/client/client.rs]: prefer AcqRel or stronger. it's not a bottleneck

**Comment by rphmeier** [comment]
When taking a snapshot it should be fine though, since that doesn't draw from the network. Actually if you go offline halfway through it will be _more likely_ to succeed because states are less likely to be pruned out.

**Comment by arkpar** [comment]
@rphmeier good point
