### PR TITLE
Fix wallet view

### LINKED ISSUE #6672: Forever loading transactions history on multi-sig
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**:  MacOS
> - **And installed**: via installer

I created a new multi-sig wallet and unable to see the transactions. It's loading forever. 

photo_2017-10-08_20-20-19

### PR DESCRIPTION
**Pull request by ngotchac**
Closes #6672

The Multisig Wallet View wouldn't load if multiple transactions happened within one block. This PR fixes it.

### CODE REVIEW

File: js/src/modals/CreateWallet/createWalletStore.js [hunk 1]
```diff
@@ -283,7 +283,8 @@ export default class CreateWalletStore {
 
     const owners = _wallet.owners.filter((owner) => !/^(0x)?0*$/.test(owner));
 
-    if (_wallet.required > owners.length) {
+    // Real number of owners is owners + creator
```
Comment (gavofyork) [inline js/src/modals/CreateWallet/createWalletStore.js]: is this true for the latest wallet code?

File: js/src/modals/CreateWallet/createWalletStore.js [hunk 2]
```diff
@@ -283,7 +283,8 @@ export default class CreateWalletStore {
...
+    if (_wallet.required > owners.length + 1) {
```
Comment (gavofyork) [inline js/src/modals/CreateWallet/createWalletStore.js]: we should now check that there are no duplicate identities between the creator and named owners.

Comment (ngotchac) [reply js/src/modals/CreateWallet/createWalletStore.js]: Is the actual wallet code ensuring that?

File: js/src/modals/CreateWallet/createWalletStore.js (hunk 1 above)
Comment (ngotchac) [reply js/src/modals/CreateWallet/createWalletStore.js]: Okay so it seems that it hasn't been updated to the latest wallet (after the last PR was merged in `paritytech/contracts`), so `msg.sender` is still one of the owner.
We _should_ update it to the latest version. Although it would be easier with this PR merged : https://github.com/paritytech/contracts/pull/74

File: js/src/modals/CreateWallet/createWalletStore.js (hunk 2 above)
Comment (gavofyork) [reply js/src/modals/CreateWallet/createWalletStore.js]: not sure about the very latest version, but i know at least one of the original versions didn't.

Comment (ngotchac) [reply js/src/modals/CreateWallet/createWalletStore.js]: At least here it doesn't : https://github.com/paritytech/contracts/blob/master/Wallet.sol#L58
We could enforce this UI-wise though, even if it's not enforced in the underlying contract.

Comment (ngotchac) [reply js/src/modals/CreateWallet/createWalletStore.js]: Done

**Comment by 5chdn** [comment]
1 Test fails.

    1) WalletDetails renders defaults:
     Invariant Violation: Could not find "store" in either the context or props of "Connect(WalletDetails)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(WalletDetails)".
      at invariant (node_modules/invariant/invariant.js:42:15)
      at new Connect (node_modules/react-redux/lib/components/connect.js:132:36)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at ShallowComponentWrapper._constructComponentWithoutOwner (node_modules/react-dom/lib/ReactCompositeComponent.js:294:16)
      at ShallowComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactShallowRenderer._render (node_modules/react-dom/lib/ReactShallowRenderer.js:126:23)
      at _batchedRender (node_modules/react-dom/lib/ReactShallowRenderer.js:79:12)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:14)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at ReactShallowRenderer.render (node_modules/react-dom/lib/ReactShallowRenderer.js:106:18)
      at ReactShallowRenderer.render (node_modules/enzyme/build/react-compat.js:158:39)
      at node_modules/enzyme/build/ShallowWrapper.js:90:26
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at node_modules/enzyme/build/ShallowWrapper.js:89:41
      at withSetStateAllowed (node_modules/enzyme/build/Utils.js:224:3)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:88:38)
      at shallow (node_modules/enzyme/build/shallow.js:19:10)
      at render (src/modals/CreateWallet/WalletDetails/walletDetails.spec.js:30:15)
      at Context.<anonymous> (src/modals/CreateWallet/WalletDetails/walletDetails.spec.js:47:12)

File: js/src/ui/Form/TypedInput/typedInput.js [hunk 3]
```diff
@@ -40,8 +40,8 @@ export default class TypedInput extends Component {
       PropTypes.string
     ]).isRequired,
 
-    accounts: PropTypes.object,
     allowCopy: PropTypes.bool,
+    allowedValues: PropTypes.array,
```
Comment (jacogr) [inline js/src/ui/Form/TypedInput/typedInput.js]: DeployContract also used `TypedInput`, don't see changes addressing the changed interface? (As well as Contract queries, Mining Settings - all passing accounts instead of allowedValues to TypedInput?)

Comment (ngotchac) [reply js/src/ui/Form/TypedInput/typedInput.js]: It's not a required prop. If empty, it should be ignored (ie. all values are allowed)

Comment (jacogr) [reply js/src/ui/Form/TypedInput/typedInput.js]: Perfect, however we are still passing `accounts` through at various places now and assuming (from the caller's perspective) it does get used, otherwise the caller shouldn't provide it. 

If those are needed, should be replaced with the real values, if not, should be removed since it creates confusion in the codebase. (And warnings when running)

Comment (ngotchac) [reply js/src/ui/Form/TypedInput/typedInput.js]: Right.

Comment (ngotchac) [reply js/src/ui/Form/TypedInput/typedInput.js]: Fixed
