### PR TITLE
Fixed receipt serialization and RPC

### LINKED ISSUE #6550: Thread '<unnamed>' panicked at 'Unexpected rlp error: RlpIsTooShort' (Ropsten Byzantium Fork)
> I'm running:
> - **Parity version**: 1.7.2
> - **Operating system**: Windows 

When running on the new Byzantium Ropsten fork and attempting to do a eth_getTransactionReceipt for this specific TxHash  0x360ae8131ff5c56694a85b4cc442921dd0cfcf8151927eda497583ad9041e9cf

curl http://localhost:8546 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x360ae8131ff5c56694a85b4cc442921dd0cfcf8151927eda497583ad9041e9cf\"],\"id\":1}" -H "Content-Type: application/json"

The following error emerges on the parity client

2017-09-19 04:21:19 UTC Imported #1700899 41da…fdb6 (0 txs, 0.00 Mgas, 0.60 ms, 0.53 KiB)
2017-09-19 04:21:20 UTC   10/25 peers      5 MiB chain   61 MiB db  0 bytes queue   23 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-19 04:21:20 UTC Imported #1700900 cd67…1744 (0 txs, 0.00 Mgas, 0.70 ms, 0.53 KiB)
thread '<unnamed>' panicked at 'Unexpected rlp error: RlpIsTooShort', src\libcore\result.rs:860
stack backtrace:
   0: hid_error
   1: hid_error
   2: hid_error
   3: hid_error
   4: hid_error
   5: hid_error
   6: hid_error
   7: hid_error
   8: <unknown>
   9: hid_error
  10: hid_error
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: hid_error
  20: <unknown>
  21: <unknown>
  22: hid_error
  23: <unknown>
  24: hid_error
  25: BaseThreadInitThunk

### PR DESCRIPTION
**Pull request by arkpar**
Closes #6550

### CODE REVIEW

File: ethcore/types/src/receipt.rs [hunk 1]
```diff
@@ -90,7 +90,7 @@ impl Decodable for Receipt {
 			};
 
 			let first = rlp.at(0)?;
-			if first.is_data() && first.data()?.len() == 1 {
```
Comment (arkpar) [inline ethcore/types/src/receipt.rs]: "0" status code is actually zero bytes

File: ethcore/types/src/receipt.rs [hunk 2]
```diff
@@ -125,6 +125,8 @@ pub struct RichReceipt {
 	pub log_bloom: LogBloom,
 	/// State root
 	pub state_root: Option<H256>,
+	/// Status byte. Optional before EIP-658.
+	pub status_code: Option<u8>,
```
Comment (rphmeier) [inline ethcore/types/src/receipt.rs]: since state root and status code are an either-or kind of thing, maybe it should be encoded as an enum instead of two separate fields? like
```rust
enum TransactionOutcome {
    Unknown(Option<H256>), // optional state root because of eip98
    Success,
    Failure,
}
```

**Comment by jackkleeman** [comment]
I can confirm this fixed the issue for me, thanks so much!
