### PR TITLE
Fix concurrent access to signer queue

### LINKED ISSUE #8799: Fix concurrent access to signer queue
Currently it's possible that two parallel RPC requests to with password to sign a signer queue entry will cause two transactions to be sent to the network.

The issue exists since we are running a multi-threaded RPC, and the signer queue doesn't have explicit lock while accessing an item.

Code: https://github.com/paritytech/parity/blob/7d7d4822a5087b24b49f2a1ddb111f2daa51a017/rpc/src/v1/impls/signer.rs#L95

So we `peek` some ID, do signing and later removed it from the queue. If nonce is not provided explicitly both threads will get a unique one and cause two same transactions to be sent.

Related #8646

### PR DESCRIPTION
**Pull request by sorpaas**
Fixes #8799.

`SignerQueue::peek` is changed to `SignerQueue::take`, which takes the request out of the queue. Subsequent redundant confirmations will not find the sender. The caller then takes the request as the handle, and gives it back to `request_confirmed` or `request_rejected` to notify senders.

### CODE REVIEW

**Comment by 5chdn** [comment]
3 tests failed.

File: rpc/src/v1/helpers/signing_queue.rs [hunk 1]
```diff
@@ -193,22 +190,26 @@ impl SigningQueue for ConfirmationsQueue {
...
+	fn request_rejected(&self, sender: ConfirmationSender) -> Option<ConfirmationRequest> {
+		debug!(target: "own_tx", "Signer: Request rejected ({:?}).", sender.request.id);
+		self.notify_result(sender, None)
 	}
 
-	fn request_rejected(&self, id: U256) -> Option<ConfirmationRequest> {
-		debug!(target: "own_tx", "Signer: Request rejected ({:?}).", id);
-		self.remove(id, None)
+	fn request_confirmed(&self, sender: ConfirmationSender, result: ConfirmationResult) -> Option<ConfirmationRequest> {
+		debug!(target: "own_tx", "Signer: Transaction confirmed ({:?}).", sender.request.id);
```
Comment (tomusdrw) [inline rpc/src/v1/helpers/signing_queue.rs]: It was `Request` since it's not necessarily a transaction (can be `eth_sign` request, or `parity_decrypt` request).
