### PR TITLE
Fix warp sync blockers detection

### LINKED ISSUE #6657: Archive +Fat +Trace node suddenly starts snapshot-sync.
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: v1.8.0-unstable-d7db8487d-20171003
> - **Operating system**: Arch Linux
> - **And installed**: from source

This should not happen, shouldn't it?

	0 ✓ user@eros ~ $ .opt/parity/target/release/parity
	2017-10-06 09:14:44  Starting Parity/v1.8.0-unstable-d7db8487d-20171003/x86_64-linux-gnu/rustc1.19.0
	2017-10-06 09:14:44  Keys path /home/user/.local/share/io.parity.ethereum/keys/Foundation
	2017-10-06 09:14:44  DB path /home/user/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
	2017-10-06 09:14:44  Path to dapps /home/user/.local/share/io.parity.ethereum/dapps
	2017-10-06 09:14:44  State DB configuration: archive +Fat +Trace
	2017-10-06 09:14:44  Operating mode: active
	2017-10-06 09:14:44  Configured for Foundation using Ethash engine
	2017-10-06 09:14:45  Updated conversion rate to Ξ1 = US$299.58 (397381730 wei/gas)
	2017-10-06 09:14:49  Removed existing file '/home/user/.local/share/io.parity.ethereum/jsonrpc.ipc'.
	2017-10-06 09:14:54  Public node URL: enode://ac1977d8753fc12dd801e87139c0fd56fed3bac136c8a9cafe4f82e147612f3232266e7f4c74d869722fd26ecefff42496ea7b2225d624d432c123f5f4ed44b8@172.16.16.11:30303
	2017-10-06 09:15:04  Syncing snapshot 0/387  #4023231    4/25 peers   81 KiB chain 7 KiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:09  Syncing snapshot 0/387  #4023231    5/25 peers   81 KiB chain 7 KiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:14  Syncing snapshot 0/387  #4023231    6/25 peers   81 KiB chain 7 KiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:19  Syncing snapshot 2/387  #4023231    6/25 peers   81 KiB chain 7 KiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:24  Syncing snapshot 3/387  #4023231    6/25 peers   81 KiB chain 7 KiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:29  Syncing snapshot 4/387  #4023231    6/25 peers   81 KiB chain 7 KiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:37  Encountered error during state restoration: Committed key already exists in database: aff8…7da3
	2017-10-06 09:15:37  Encountered error during state restoration: Incomplete snapshot: 1 contract codes not found.
	2017-10-06 09:15:39  Syncing #4023231 66f3…0d2a     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4023224    4/25 peers   81 KiB chain 7 KiB db 0 bytes queue 181 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:44  Syncing #4023231 66f3…0d2a     0 blk/s    0 tx/s   0 Mgas/s     72+  241 Qed  #4023555    4/25 peers   81 KiB chain 60 KiB db 13 MiB queue 211 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:49  Syncing #4023237 8811…2015     1 blk/s   70 tx/s   3 Mgas/s     17+  604 Qed  #4023866    4/25 peers   119 KiB chain 304 KiB db 30 MiB queue 226 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:54  Syncing #4023262 3e93…c14b     5 blk/s  237 tx/s  11 Mgas/s     48+  689 Qed  #4024004    5/25 peers   347 KiB chain 766 KiB db 34 MiB queue 978 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:15:59  Syncing #4023284 5fa8…51e2     4 blk/s  283 tx/s  12 Mgas/s      0+  833 Qed  #4024120    6/25 peers   495 KiB chain 1 MiB db 40 MiB queue 2 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:16:04  Syncing #4023308 e616…10a5     4 blk/s  305 tx/s  16 Mgas/s      0+  936 Qed  #4024247    6/25 peers   959 KiB chain 1 MiB db 48 MiB queue 905 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:16:09  Syncing #4023344 5bd4…0877     7 blk/s  286 tx/s  13 Mgas/s      0+  900 Qed  #4024247    6/25 peers   996 KiB chain 2 MiB db 47 MiB queue 905 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:16:14  Syncing #4023385 3ca9…1507     8 blk/s  298 tx/s  14 Mgas/s      0+  860 Qed  #4024247    6/25 peers   1 MiB chain 2 MiB db 45 MiB queue 905 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:16:19  Syncing #4023415 2d88…41b1     6 blk/s  286 tx/s  13 Mgas/s      0+  828 Qed  #4024247    6/25 peers   2 MiB chain 3 MiB db 44 MiB queue 905 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:16:29  Syncing #4023472 3970…8962     5 blk/s  312 tx/s  13 Mgas/s      0+  772 Qed  #4024247    6/25 peers   2 MiB chain 3 MiB db 41 MiB queue 905 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
	2017-10-06 09:16:39  Syncing #4023546 1dd4…c3db     7 blk/s  296 tx/s  13 Mgas/s    264+  719 Qed  #4024628    6/25 peers   2 MiB chain 4 MiB db 48 MiB queue 317 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

### PR DESCRIPTION
**Pull request by arkpar**
Closes #6657

### CODE REVIEW

File: parity/run.rs [hunk 1]
```diff
@@ -496,7 +497,21 @@ pub fn execute(cmd: RunCmd, can_restart: bool, logger: Arc<RotatingLogger>) -> R
...
+	if warp_sync {
+		// Logging is not initialized yet, so we print directly to stderr
+		if fat_db {
+			warn!("Warning: Warp Sync is disabled because Fat DB is turned on.");
+			warp_sync = false;
+		} else if tracing {
+			warn!("Warning: Warp Sync is disabled because tracing is turned on.");
+			warp_sync = false;
+		} else if algorithm != Algorithm::OverlayRecent {
+			warn!("Warning: Warp Sync is disabled because of non-default pruning mode.");
```
Comment (rphmeier) [inline parity/run.rs]: can we rephrase to "because pruning is disabled"? we don't really support other versions anymore.
