### PR TITLE
Fix dappIcon & Fix Signer Pending

### LINKED ISSUE #7219: DappIcon in UI does not load in all cases, i.e. when dappUrl is set

### PR DESCRIPTION
**Pull request by amaurymartiny**
- DappIcons all display correctly. Fix #7219
- Put signerPending from js-ui into this repo.

PS: @tomusdrw I finally decided not to change to the notification UI in the extension for now: it was way too much headache (popup placed randomly, icons not loading...) for not much result. We can do that when we decide to clean the extension, cf your issue.

### CODE REVIEW

File: js/test/babel.js [hunk 1]
```diff
@@ -14,13 +14,5 @@
...
-require('babel-register')({
-  ignore: function (filename) {
-    if (filename.indexOf('node_modules') !== -1) {
-      return filename.indexOf('@parity') === -1;
-    }
-
-    return false;
-  }
-});
+require('babel-register')();
```
Comment (amaurymartiny) [inline js/test/babel.js]: Explanation: All `@parity/*` export transpiled JS, so no need to babelify them again as done before.

Comment (jacogr) [reply js/test/babel.js]: Good catch.
