### PR TITLE
`evm bench` fix broken dependencies

### LINKED ISSUE #9124: Error during compilation (Fedora)
Parity `master` at `9dc512349a8dd33df4160d1bdd7b7e61f13c9604`, on Fedora. 
Trying to run some benchmarks with `home/user/.cargo/bin/cargo bench -p ethcore`, but hitting the following error during compilation: 

```
   Compiling ethcore v1.12.0 (file:///home/user/workspace/parity/ethcore)
error[E0463]: can't find crate for `util`
  --> ethcore/benches/evm.rs:20:1
   |
20 | extern crate ethcore_util as util;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `ethcore`.
warning: build failed, waiting for other jobs to finish...
```
Any help appreciated!

### PR DESCRIPTION
**Pull request by niklasad1**
Closes #9124 

Benchmarks of the `evm` used stale versions of a couple of crates that
this commit fixes!

### CODE REVIEW

**Comment by niklasad1** [comment]
Hrm, weird I didn't see those warnings let me try again!

File: ethcore/benches/evm.rs [hunk 1]
```diff
@@ -62,8 +61,7 @@ fn bn_128_mul(b: &mut Bencher) {
 fn sha256(b: &mut Bencher) {
 	use parity_crypto::digest::sha256;
 
-	let mut input: [u8; 256] = [0; 256];
-	let mut out = [0; 32];
```
Comment (niklasad1) [inline ethcore/benches/evm.rs]: This was actually never used!
