### PR TITLE
bigint upgraded to version 3.0

### LINKED ISSUE #5964: Can't use ethcore_bigint within dylib on macOS
It is very similar to #4836

Repo with demo: https://github.com/ssbb/parity_test

error:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/ssbb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/ssbb/Workspace/test_parity_lib/target/debug/deps/test_parity.0.o" "-o" "/Users/ssbb/Workspace/test_parity_lib/target/debug/deps/libtest_parity.dylib" "/Users/ssbb/Workspace/test_parity_lib/target/debug/deps/test_parity.crate.metadata.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/ssbb/Workspace/test_parity_lib/target/debug/deps" "-L" "/Users/ssbb/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libethcore_bigint-7344c2b2d83cd66f.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libbigint-bbf8e67a8f1e8f1b.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libbyteorder-026efa39a80f7fd2.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/librand-f05bf79cdd272742.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/liblibc-3ab122365045951f.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/librustc_serialize-44639db696df1ac0.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libheapsize-26987f31c5a5aa1c.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libstd-10990d3dd566b117.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libpanic_unwind-324d162f9573503b.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libunwind-dbf02348e1b34fa8.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/liballoc-2fabd6646d858a79.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/liballoc_system-21953a3f49a8455e.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/liblibc-fafc9c96cb711f35.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libstd_unicode-6952d1a853d57ece.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/librand-0152ce8477f43185.rlib" "-Wl,-force_load,/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libcore-f96c2e418b58c2bd.rlib" "/var/folders/pm/xns2qx795dx2fdc09mtplzcw0000gn/T/rustc.5TXF1sNTU5vl/libcompiler_builtins-b67e11e490b1a65b.rlib" "-l" "System" "-l" "resolv" "-l" "pthread" "-l" "c" "-l" "m" "-dynamiclib" "-Wl,-dylib"
  = note: Undefined symbols for architecture x86_64:
            "_je_malloc_usable_size", referenced from:
                heapsize::heap_size_of_impl::h9789dd2638d56a99 in libheapsize-26987f31c5a5aa1c.rlib(heapsize-26987f31c5a5aa1c.0.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error(s)

error: Could not compile `test_parity_lib`.
```

Looks like the issue is fixed already, but not sure why I got this error then :(

OS: macOS 10.12.5
rustc 1.20.0-nightly (3bfc18a96 2017-06-29) (tried on 1.18 too)
 parity: master (tried 1.6.8 release too)

### PR DESCRIPTION
**Pull request by debris**
changes:
- upgraded `bigint` crate to version `3.0.0`
- moved `util/benches/bigint.rs` to `bigint` repo
- updated `ethcore-bigint` so it does not depend on `heapsize` crate by default, fixes #5964
- replaced deprecated `rustc-serialize` with smaller `rustc-hex` where possible. rustc-serialize is left only where it's used for json/cli decoding. I will make a separate issue for this - #5988
- removed global `rustc_serialize` reexports from `util/src/standard.rs`

### CODE REVIEW

File: evmbin/src/display/json.rs [hunk 1]
```diff
@@ -122,7 +122,7 @@ impl trace::VMTracer for Informant {
 	fn prepare_subtrace(&self, code: &[u8]) -> Self where Self: Sized {
 		let mut vm = Informant::default();
 		vm.depth = self.depth + 1;
-		vm.code = code.into_vec();
+		vm.code = code.to_vec();
```
Comment (debris) [inline evmbin/src/display/json.rs]: this change is unrelated to this pr, but was needed to compile `evmbin`
